---
host: "192.168.1.11"
port: 22
connectionTimeout: 1000
readTimeout: 3000
retryConnectionInterval: 3000
numClockSamples: 3
clockInterval: 300000
clockTimeout: 1000
restartClockSyncDelay: 100
statusInterval: 20
startQueryDelay: 150
motorCommandInterval: 700
scanCommandInterval: 700

engine: /engines/sala

engines:
  manual:
    builder: org.mmarini.wheelly.engines.Builders.manual
# Linux
#    joystickPort: "Mega World USB Game Controllers"
# Windows
#    joystickPort: "USB Game Controllers"
  stop:
    builder: org.mmarini.wheelly.engines.Builders.stop
  sequence:
    builder: org.mmarini.wheelly.engines.Builders.sequence
    targets:
      - x: 0
        y: 0
      - x: 1
        y: 1
      - x: 1
        y: 0
    thresholdDistance: 0.1
  sala:
    builder: org.mmarini.wheelly.engines.Builders.findPath
    targets:
      - x: 2.3
        y: 3
      - x: 0
        y: 0
    thresholdDistance: 0.1
    safeDistance: 0.3
  lab:
    builder: org.mmarini.wheelly.engines.Builders.findPath
    targets:
      - x: 0.8
        y: 0
    thresholdDistance: 0.1
    safeDistance: 0.3
  gotoTest:
    builder: org.mmarini.wheelly.engines.Builders.gotoTest
    targets:
      - x: 1
        y: 0
    thresholdDistance: 0.1
    safeDistance: 0.3
  avoid:
    builder: org.mmarini.wheelly.engines.Builders.avoidObstacle

